# Generated by Django 4.2.24 on 2025-09-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('grams', 'grams'), ('cups', 'cups'), ('pounds', 'pounds'), ('ounces', 'ounces'), ('teaspoons', 'teaspoons'), ('tablespoons', 'tablespoons'), ('quarts', 'quarts'), ('pints', 'pints'), ('gallons', 'gallons')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('spice', 'Spice'), ('herb', 'Herb'), ('seafood', 'Seafood'), ('nut', 'Nut'), ('legume', 'Legume'), ('oil', 'Oil'), ('sweetener', 'Sweetener'), ('beverage', 'Beverage'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
